import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/AppSidebar";
import { cookies } from "next/headers";
import AppNavbar from "@/components/navbar/AppNavbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { ContextProvider } from "@/context/Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextDash",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={'dark'}
          enableSystem={false}

          disableTransitionOnChange
        >
          <ContextProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar/>
              <main className="w-full">
                <AppNavbar />

                <div className="">{children}</div>

              </main>
            </SidebarProvider>
          </ContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
